version: '3'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: claudiupopa/app:latest
    networks: 
      - appnet
    volumes:
      - .:/var/www/html
    ports:
      - ${APP_PORT}:80
      - 5173:5173
    environment:
      - MY_UID=${MY_UID}
      - MY_GID=${MY_GID}
    working_dir: /var/www/html

  redis:
    image: redis:alpine
    networks: 
      - appnet
    volumes:
      - cachedata:/data

  db:
    image: mysql:5.7
    networks:
      - appnet
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - ${DB_PORT}:3306
    volumes:
      - dbdata:/var/lib/mysql
  
  node:
    user: root
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: claudiupopa/node:latest
    networks:
     - appnet
    volumes:
     - .:/opt
    environment:
      - MY_UID=${MY_UID}
      - MY_GID=${MY_GID}
    working_dir: /opt
    command: echo hi

  queue:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    environment:
      - MY_UID=${MY_UID}
      - MY_GID=${MY_GID}
    entrypoint: ['php', '/var/www/html/artisan', 'queue:work']
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local